### ISSUE TITLE
Evaluation of NER frameworks

### ISSUE THREAD

**Issue by BurhanOtour** [SmartBV2/Fact_Checker#2]
Currently we come up with two NLP toolbox:
1. FOX ( http://aksw.org/Projects/FOX.html )
2. CoreNLP ( https://stanfordnlp.github.io/CoreNLP/ )

We need to decide which one of these frameworks we are going to use: 
- What are the main characteristics of each frameworks. 
- The tools that may best serves our needs.

**Comment by BurhanOtour** [comment]
Could you please use Wiki to add your evaluation to both libraries ? @vineete2

**Comment by VarmaHub** [comment]
Since FOX is considered as our final choice, closing the issue.
