### ISSUE TITLE
include wikij in the project source code

### ISSUE THREAD

**Issue by BurhanOtour** [SmartBV2/Fact_Checker#5]
https://github.com/fastily/jwiki

**Comment by VarmaHub** [comment]
How would this help us? Are we going to try creating corpus using this?

**Comment by BurhanOtour** [comment]
@VarmaHub I am just checking if that can be helpful to us.

**Comment by VarmaHub** [comment]
@BurhanOtour Instead of crawling each page using Jwiki, how about using [DBpedia ](http://downloads.dbpedia.org/2016-04/) corpus?

**Comment by VarmaHub** [comment]
Since Corpus choice is made, closing this issue.
