### ISSUE TITLE
Corpus selection and storage

### ISSUE THREAD

**Issue by VarmaHub** [SmartBV2/Fact_Checker#7]
Hi,

How about RDF dump?

Selection: [DBpedia](http://wiki.dbpedia.org/downloads-2016-10)
Sorage: [ Apache Jena ](https://jena.apache.org/documentation/tdb/index.html)

Or use NYT2013 dump and preprocess it for FOX. Any new thoughts?

**Comment by vineete2** [comment]
Storage : form of TTL Files

**Comment by VarmaHub** [comment]
As of no further thoughts and being NYT2013 is considered as a final choice, for now, closing the issue.
